"""Compute agent: execute DSL SQL on configured data store."""

import pandas as pd

from agents.base_agent import BaseAgent


class ComputeAgent(BaseAgent):
    """Execute SQL generated by DSLQueryAgent and return tabular results."""

    def __init__(self, data_store):
        super().__init__("计算执行智能体", "执行DSL生成的SQL并返回结果")
        self.store = data_store

    def run(self, input_data: dict) -> dict:
        dispatch = input_data.get("dispatch", {})
        dsl_query = input_data.get("dsl_query", {})

        self.log("开始执行计算...")
        source_id = str(dispatch.get("source_id", "")).strip() or str(input_data.get("source_id", "")).strip()

        final_df = pd.DataFrame()
        try:
            if not isinstance(dsl_query, dict):
                raise ValueError("DSL查询产物非法")

            dsl_payload = dsl_query.get(source_id, {})
            if not isinstance(dsl_payload, dict) or not dsl_payload:
                raise ValueError("DSL未产出结果，无法执行SQL")

            dsl_error = str(dsl_payload.get("error", "")).strip()
            if dsl_error:
                raise ValueError(f"DSL生成失败: {dsl_error}")

            sql_text = str(dsl_payload.get("sql", "")).strip()
            if not sql_text:
                raise ValueError("DSL未产出可执行SQL")

            if not hasattr(self.store, "execute_sql"):
                raise ValueError("当前数据存储不支持 execute_sql，无法执行DSL SQL")

            self.log(f"  数据源 {source_id}: 使用 SQL 执行")
            result = self.store.execute_sql(source_id, sql_text)

            if isinstance(result, pd.DataFrame):
                final_df = result
            else:
                final_df = pd.DataFrame(result)

            self.log(f"  数据源 {source_id}: 获得 {len(final_df)} 条结果")
        except Exception as error:
            self.log(f"  数据源 {source_id} 执行失败: {error}")
            final_df = pd.DataFrame()

        self.log(f"计算执行完成: 共{len(final_df)}条结果")
        return {
            **input_data,
            "compute_result": final_df.to_dict(orient="records"),
            "compute_result_df": final_df,
        }

